package Screens;

import Classes.Lib;
import Classes.PetInventory;
import Classes.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class ScreenAdminMenu extends javax.swing.JFrame {

    PetInventory petInventory;
    /**
     * Creates new form ScreenAdminMenu
     */
    public ScreenAdminMenu(PetInventory petInventory) {
        initComponents();
        this.petInventory = petInventory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonNewClient = new javax.swing.JButton();
        jButtonNewSeller = new javax.swing.JButton();
        jButtonNewVet = new javax.swing.JButton();
        jButtonNewProduct = new javax.swing.JButton();
        jButtonNewTask = new javax.swing.JButton();
        jButtonSellProduct = new javax.swing.JButton();
        jButtonSellTask = new javax.swing.JButton();
        jButtonListRole = new javax.swing.JButton();
        jButtonListClients = new javax.swing.JButton();
        jButtonListTaskOrder = new javax.swing.JButton();
        jButtonRegisterTreatment = new javax.swing.JButton();
        jButtonResetStock = new javax.swing.JButton();
        jButtonPayBill = new javax.swing.JButton();
        jButtonGenerateReports = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonListProduct = new javax.swing.JButton();
        jButtonSearchTask = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Admin Menu");

        jButtonNewClient.setText("New Client");
        jButtonNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewClientActionPerformed(evt);
            }
        });

        jButtonNewSeller.setText("New Seller");
        jButtonNewSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSellerActionPerformed(evt);
            }
        });

        jButtonNewVet.setText("New Vet");
        jButtonNewVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewVetActionPerformed(evt);
            }
        });

        jButtonNewProduct.setText("New Product");
        jButtonNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewProductActionPerformed(evt);
            }
        });

        jButtonNewTask.setText("New Task");
        jButtonNewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewTaskActionPerformed(evt);
            }
        });

        jButtonSellProduct.setText("Sell Product");
        jButtonSellProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellProductActionPerformed(evt);
            }
        });

        jButtonSellTask.setText("Sell Task");
        jButtonSellTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellTaskActionPerformed(evt);
            }
        });

        jButtonListRole.setText("List Role");
        jButtonListRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListRoleActionPerformed(evt);
            }
        });

        jButtonListClients.setText("List Clients");
        jButtonListClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListClientsActionPerformed(evt);
            }
        });

        jButtonListTaskOrder.setText("List Task Order");
        jButtonListTaskOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListTaskOrderActionPerformed(evt);
            }
        });

        jButtonRegisterTreatment.setText("Register Treatment");
        jButtonRegisterTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterTreatmentActionPerformed(evt);
            }
        });

        jButtonResetStock.setText("Reset Stock");
        jButtonResetStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetStockActionPerformed(evt);
            }
        });

        jButtonPayBill.setText("Pay the Bill");
        jButtonPayBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayBillActionPerformed(evt);
            }
        });

        jButtonGenerateReports.setText("Generate Reports");
        jButtonGenerateReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateReportsActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonListProduct.setText("List Product");
        jButtonListProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListProductActionPerformed(evt);
            }
        });

        jButtonSearchTask.setText("Search Task");
        jButtonSearchTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonListProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonPayBill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRegisterTreatment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonListClients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSellTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNewTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNewVet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                    .addComponent(jButtonNewClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonResetStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonListTaskOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                    .addComponent(jButtonListRole, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSellTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNewSeller, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNewProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonGenerateReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSearchTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewVet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSellProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSellTask, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListRole, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListClients, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListTaskOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegisterTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResetStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPayBill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGenerateReports, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchTask, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        String message = "Do you really want to exit the Admin Menu?";
        String title = "Confirmation";
        int answer = JOptionPane.showConfirmDialog(this,  message, title, JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION){
            PetInventory.back();
        }
    }

    private void jButtonGenerateReportsActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenReports(petInventory));         
    }

    private void jButtonPayBillActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenPayBill(petInventory));   
    }

    private void jButtonResetStockActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenResetStock(petInventory)); 
    }

    private void jButtonRegisterTreatmentActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenRegisterTreatment(petInventory)); 
    }

    private void jButtonListTaskOrderActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenListTaskOrder(petInventory)); 
    }

    private void jButtonListClientsActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenListClients(petInventory)); 
    }

    private void jButtonListRoleActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenListRole(petInventory)); 
    }

    private void jButtonSellTaskActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenSellTask(petInventory)); 
    }

    private void jButtonSellProductActionPerformed(java.awt.event.ActionEvent evt) {
        ArrayList<Product> shoppingBag = new ArrayList<>();
        petInventory.Next(new ScreenSellProduct(petInventory, shoppingBag)); 
    }

    private void jButtonNewTaskActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenNewTask(petInventory)); 
    }

    private void jButtonNewProductActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenNewProduct(petInventory)); 
    }

    private void jButtonNewVetActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenNewRole(petInventory)); 
    }

    private void jButtonNewSellerActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new SreenNewRole(petInventory)); 
    }

    private void jButtonNewClientActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenNewClient(petInventory, false)); 
    }

    private void jButtonListProductActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenListProduct(petInventory)); 
    }

    private void jButtonSearchTaskActionPerformed(java.awt.event.ActionEvent evt) {
        petInventory.Next(new ScreenSearchTask(petInventory)); 

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearchTask;
    private javax.swing.JButton jButtonNewClient;
    private javax.swing.JButton jButtonNewProduct;
    private javax.swing.JButton jButtonNewTask;
    private javax.swing.JButton jButtonNewSeller;
    private javax.swing.JButton jButtonNewVet;
    private javax.swing.JButton jButtonGenerateReports;
    private javax.swing.JButton jButtonListClients;
    private javax.swing.JButton jButtonListRole;
    private javax.swing.JButton jButtonListTaskOrder;
    private javax.swing.JButton jButtonListProduct;
    private javax.swing.JButton jButtonPayBill;
    private javax.swing.JButton jButtonRegisterTreatment;
    private javax.swing.JButton jButtonResetStock;
    private javax.swing.JButton jButtonSellProduct;
    private javax.swing.JButton jButtonSellTask;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
