package Screens;

import Classes.PetInventory;
import javax.swing.JOptionPane;

public class ScreenVetMenu extends javax.swing.JFrame{
    PetInventory petInventory;
    /**
     * Creates new form ScreenVetMenu
     */
    public ScreenVetMenu(PetInventory petInventory) {
        initComponents();
        this.petInventory = petInventory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonListClients = new javax.swing.JButton();
        jButtonListTaskOrder = new javax.swing.JButton();
        jButtonSearchTask= new javax.swing.JButton();
        jButtonRegisterTreatment = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vet Menu");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("Vet Menu");

        jButtonListClients.setText("List Clients");
        //jButtonListClients.addActionListener(new java.awt.event.ActionListener() {
            //public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jButtonListClientsActionPerformed(evt);
            //}
       // });

        jButtonListTaskOrder.setText("List Task Order");
       // jButtonListTaskOrder.addActionListener(new java.awt.event.ActionListener() {
           // public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jButtonListTaskOrderActionPerformed(evt);
            //}
       // });

        jButtonSearchTask.setText("Search Task");
        //jButtonSearchTask.addActionListener(new java.awt.event.ActionListener() {
            //public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jButtonSearchTaskActionPerformed(evt);
           // }
        //});

        jButtonRegisterTreatment.setText("Register Treatment");
        //jButtonRegisterTreatment.addActionListener(new java.awt.event.ActionListener() {
          //  public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jButtonRegisterTreatmentActionPerformed(evt);
            //}
       // });

        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonListClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonListTaskOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSearchTask, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                            .addComponent(jButtonRegisterTreatment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButtonBack)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jButtonListClients, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListTaskOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSearchTask, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegisterTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonBack))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   // private void jButtonListClientsActionPerformed(java.awt.event.ActionEvent evt) {
        //calls the client list screen and inserts it in the screen history
       // petInventory.next(new ScreenListClients(petInventory)); 
    //}

   // private void jButtonListTaskOrderActionPerformed(java.awt.event.ActionEvent evt) {
        //calls the Task Order list screen and inserts it in the screen history
       // petInventory.next(new ScreenListTaskOrder(petInventory)); 
    //}

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {
        // Vet back button action
        String message = "Do you really want to exit the Vet Menu?";
        String title = "Confirmation";
        int answer = JOptionPane.showConfirmDialog(this,  message, title, JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION){
            petInventory.back();
        }
    }

   // private void jButtonSearchTaskActionPerformed(java.awt.event.ActionEvent evt) {
        //calls the Task Search list screen and inserts it in the screen history
       // petInventory.next(new ScreenSearchTask(petInventory)); 
    //}

   // private void jButtonRegisterTreatmentActionPerformed(java.awt.event.ActionEvent evt) {
        //calls the Register Treatment list screen and inserts it in the screen history
        //petInventory.next(new ScreenRegisterTreatment(petInventory)); 
   // }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearchTask;
    private javax.swing.JButton jButtonListClients;
    private javax.swing.JButton jButtonListTaskOrder;
    private javax.swing.JButton jButtonRegisterTreatment;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 }
